### ISSUE TITLE
[NEW] Memos

### ISSUE THREAD

**Issue by rensatsu** [HowItLooks-dev/projects#9]
Project Github url: https://github.com/usememos/memos

*optional*
Short explaination of the project:
A lightweight note-taking solution. The pain-less way to create meaningful notes.

*optional* 
longer explaination about project:
A privacy-first, lightweight note-taking solution that allows you to effortlessly capture and share your ideas.
Create and manage your notes in plain text, utilizing Markdown for easy formatting, without the complications of rich text editing.
Personalize your notes and share them easily with others through intuitive collaboration features.
Integrate seamlessly with third-party applications and unlock new possibilities through RESTful API support.

Homepage: https://www.usememos.com/

Docker Compose: https://www.usememos.com/docs/install/container-install#docker-compose

Screenshots:
Main page:
![image](https://github.com/user-attachments/assets/0e0e49dc-bb18-4d2d-b145-aaa9487968b7)
Editor:
![image](https://github.com/user-attachments/assets/e9e4b24a-2ed0-418f-b14b-36856c7934bb)

**Comment by OfficeRat** [comment]
Page created, gathering more images

**Comment by OfficeRat** [comment]
images added https://howitlooks.dev/projects/memos
